# Spring properties
spring:
  application:
    name: fp-apigateway  # Identify this application


# HTTP Server
server:
  port: ${server_port:8181}   # HTTP port
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.3:1111/eureka/
#      defaultZone: ${eureka_url:http://fp-eureka:1111/eureka/}
  instance:
#    instance-id:  ${spring.application.name}:${server.port}
    instance-id:  ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
# Api-Gate-Way
zuul:
  prefix: /fp/api
  routes:
    auth-service:
      path: /auth-service/**
      serviceId: AUTH-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie
      
    product-service:
      path: /admin-service/**
      serviceId: ADMINISTRATOR-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie
      
