# Spring properties
spring:
  application:
    name: FPApiGateway  # Identify this application


# HTTP Server
server:
  port: 8181   # HTTP port
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
# Api-Gate-Way
zuul:
  prefix: /fp/api
  routes:
    auth-service:
      path: /auth-service/**
      serviceId: AUTH-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie
      
    product-service:
      path: /admin-service/**
      serviceId: ADMISTRATOR-SERVICE
      sensitiveHeaders: Cookie,Set-Cookie
      
