# Spring properties
spring:
  application:
    name: FPApiGateway  # Identify this application


# HTTP Server
server:
  port: ${ADMIN_SERVER_PORT:9999}   # HTTP port
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

      
# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
# Api-Gate-Way
zuul:
  prefix: /api
