# Spring properties
spring:
  application:
    name: FPAUTH-SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
liquibase:
  user: ${RDS_USERNAME}
  password: ${RDS_PASSWORD}
  url: ${RDS_URL}

# HTTP Server
server:
  port: 0
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Auth JWT
jwt:
  header: Authorization
  secret: nearshore_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh
