# Spring properties
spring:
  application:
    name: FPCloudConfig  # Identify this application

# HTTP Server
server:
  port: 9999  # HTTP port
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
     preferIpAddress: true
     leaseRenewalIntervalInSeconds: 1
     leaseExpirationDurationInSeconds: 2
