#Application Name
spring:
  application:
    name: FPEureka

#HTTP Server
server: 
  port: ${random.int[1024,65535]}

#Eureka Configuration Properties
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
   enableSelfPreservation: false
