#Application Name
spring:
  application:
    name: FPEureka

#HTTP Server
server: 
  port: 1111

#Eureka Configuration Properties
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://localhost:1111/eureka/
  server:
     enableSelfPreservation: true
     renewal-threshold-update-interval-ms: 900000
     renewal-percent-threshold: 0.85
     eviction-interval-timer-in-ms: 60000
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
