
#Application Name
spring:
  application:
    name: FPEureka

#HTTP Server
server: 
  port: 1111

#Eureka Configuration Properties
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
   waitTimeInMsWhenSyncEmpty: 0
   enableSelfPreservation: false
