# Spring properties
spring:
  application:
    name: admistrator-service
  datasource:
    url: jdbc:mysql://mysql:3306/demo
    username: demo_user
    password: demo_pass
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none


# HTTP Server
server:
  port: 0
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Auth JWT
jwt:
  header: Authorization
  secret: nearshore_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh
