# Spring properties
spring:
  application:
    name: administrator-service
  # Spring JDBC configuration
  datasource:
    url:      ${RDS_URL}
    data-username: ${RDS_USERNAME}
    username: ${RDS_USERNAME}
    data-password: ${RDS_PASSWORD}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver

  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage!
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

# HTTP Server
server:
    port: 0
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    instance-id:  ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.int}}
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Auth JWT
jwt:
  header: Authorization
  secret: nearshore_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh
