# Spring properties
spring:
  application:
    name: admistrator-service
  datasource:
    url: jdbc:mysql://mysql:3306/focalpoint-prod
    username: focalpoint
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none


# HTTP Server
server:
  port: ${random.int[10000,65000]}
  
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Auth JWT
jwt:
  header: Authorization
  secret: nearshore_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh
      

  # Spring JDBC configuration
  datasource:
    url:      jdbc:mysql://127.0.0.1:3306/focalpoint-prod
    rname: focalpoint
    password: 123456

  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage!
      ddl-auto: none
    show-sql: true
