# Spring properties
spring:
  application:
    name: admistrator-service
  # Spring JDBC configuration
  datasource:
    url:      jdbc:mysql://127.0.0.1:3306/focalpoint-prod
    data-username: focalpoint
    username: focalpoint
    data-password: 123456
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage!
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

# HTTP Server
server:
    port: 0
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    instance-id:  ${spring.application.name}:${random.int[8280,8289]}
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# Auth JWT
jwt:
  header: Authorization
  secret: nearshore_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh
